config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get '/users/guest_sign_in', to: 'users/sessions#guest_login'
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post
  before_action :admin_limit

  def create
    if current_user != @post.user
      like = current_user.likes.new(post_id: @post.id)
      like.save
    end
  end

  def destroy
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def admin_limit
    redirect_back(fallback_location: posts_path) if current_user.admin?
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if post.liked_by?(current_user) %>
	<%= link_to post_likes_path(post), method: :delete, remote: true do %>
		<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
		<%= post.likes.count %>
	<% end %>
<% else %>
	<%= link_to post_likes_path(post), method: :post, remote: true do %>
		<i class="far fa-heart" aria-hidden="true" style="color: red;"></i>
		<%= post.likes.count %>
	<% end %>
<% end %>

app/views/likes/create.js.erb
$('.post_<%= @post.id %>').html("<%= j(render 'likes/like', post: @post) %>");

app/views/likes/destroy.js.erb
$('.post_<%= @post.id %>').html("<%= j(render 'likes/like', post: @post) %>");