config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get '/users/guest_sign_in', to: 'users/sessions#guest_login'
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable, :timeoutable
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :follower, class_name: "Relationship",
                      foreign_key: "follower_id",
                      dependent: :destroy
  has_many :followed, class_name: "Relationship",
                      foreign_key: "followed_id",
                      dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :followers_user, through: :followed, source: :follower

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 3, maximum: 20 }
  attachment :profile_image

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーをフォロー解除する
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  # ゲストユーザー取得
  def self.guest
    find_by(email: 'guest_user@gmail.com')
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # アカウント登録後のリダイレクト先
  def after_sign_up_path_for(resource)
    posts_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def guest_login
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: "ゲストユーザーとしてログインしました。"
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  # ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    posts_path
  end

  # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: :destroy
  before_action :check_guest, only: :destroy

  def index
    if user_signed_in?
      @users =  User.where.not(id: current_user.id, admin: true).page(params[:page]).per(9)
    else
      @users =  User.where.not(admin: true).page(params[:page]).per(9)
    end
  end

  def show
    @my_posts = @user.posts.order(created_at: "DESC").page(params[:page]).per(3)
    @follow_users = @user.following_user.page(params[:page]).per(3)
    @follower_users = @user.followers_user.page(params[:page]).per(3)
    @like_posts = @user.likes.page(params[:page]).per(3)
  end

  def edit
    if @user.admin?
      flash[:alert] = "管理者ユーザーはプロフィール編集できません。"
      redirect_back(fallback_location: users_path)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:alert] = "#{@user.name}さんを削除しました。"
    redirect_back(fallback_location: users_path)
  end

  def search
    if user_signed_in?
      @search = User.where.not(id: current_user.id, admin: true).ransack(params[:q])
    else
      @search = User.where.not(admin: true).ransack(params[:q])
    end
    @search_users = @search.result.page(params[:page])
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def admin_user
    redirect_to(users_path) unless current_user.admin?
  end

  def check_guest
    if @user.email == "guest_user@gmail.com"
      redirect_to posts_path, alert: "ゲストユーザーは削除できません。"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<% if user_signed_in? %>
	<% if current_user.following?(user) %>
  		<%= link_to 'フォロー中', unfollow_path(user.id), method: :post, remote: true, class: 'btn btn-primary rounded-pill d-flex align-items-center justify-content-center' %>
	<% else %>
  		<%= link_to 'フォロー', follow_path(user.id), method: :post, remote: true, class: 'btn btn-primary rounded-pill d-flex align-items-center justify-content-center' %>
  	<% end %>
<% end %>

app/views/users/_user_card.html.erb
<div class="card col-3 offset-1 d-flex rounded-lg my-2">
	<div class="card-img-top d-flex align-items-center justify-content-center">
		<%= link_to user_path(user) do %>
			<%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "150x150", class: "rounded-circle" %>
		<% end %>
	</div>
	<div class="card-body">
		<span class="d-flex align-items-center justify-content-center font-weight-bold" style="font-size: 20px;"><%= link_to user.name, user_path(user),class: "text-dark" %></span>

		<% if user_signed_in? && current_user.admin? %>
			<span class="d-flex align-items-center justify-content-center font-weight-bold" style="font-size: 20px;"><%= link_to '削除', user_path(user), method: :delete, class: 'btn btn-danger' %></span>
		<% else %>
			<div class="follow_<%= user.id %> mt-2">
				<%= render "users/follow_form", user: user %></div>
   		<% end %>
 	</div>
</div>

app/views/users/_user_list.html.erb
<div class="scroll">
	<div class="row">
		<% users.each do |user| %>
			<%= render "user_card", user: user %>
		<% end %>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container">
    <h2 class="title d-flex"><span class="border-bottom mx-auto mb-5">プロフィール編集</span></h2>

    <%= form_for(@user) do |f| %>
        <%= render "shared/error_messages", model: f.object %>

        <div class="media col-8 d-flex mx-auto">
            <div class="user-image col-5 d-flex">
                <div class="form-group">
                    <label>
                    <div class="form_main">
                        <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "150x150", class: 'image_form' %>
                    </div>
                    <div class="form_sub">
                        <%= f.attachment_field :profile_image, class: 'form-control-file' %>
                    </div>
                    </label>
                </div>
            </div>

            <div class="user-inf media-body col-7">
                <div class="form-group">
                    <%= f.label :name, "名前" %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= f.label :introduction, "自己紹介" %>
                    <%= f.text_area :introduction, class: 'form-control' %>
                </div>
            </div>
        </div>

        <div class="col-8 d-flex mx-auto mt-5">
            <div class="mx-auto">
                <%=link_to 'キャンセル', user_path(@user), class: "btn-lg btn-light mr-2" %>
                <%= f.submit '変更を保存', class: 'btn-lg btn-outline-dark' %>
            </div>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	<%= render "shared/notice", notice: notice %>
	<%= render "shared/alert", alert: alert %>

	<h2 class="title d-flex"><span class="border-bottom mx-auto mb-5">すべてのユーザー</span></h2>

	<div id="scroll">
		<%= render "user_list", users: @users %>
		<%= link_to_next_page @users, '次のページ', class: "next" %>
	</div>
	<button class="button" type="button">もっと見る</button>
	<%= render "shared/scroll_setting" %>
</div>

app/views/users/search.html.erb
<div class="container">
	<%= render "shared/alert", alert: alert %>

	<div class="row">
		<div class="col-6 mx-auto my-3">
			<%= search_form_for @search, url: search_users_path do |f| %>
      			<%= f.search_field :name_cont, class: "form-control", placeholder: "ユーザーを検索" %>
      			<%= f.submit '検索', class: "btn btn-success d-none" %>
    		<% end %>
    	</div>
   	</div>

   	<ul class="nav nav-pills col-8 mx-auto my-4 p-0" role="tablist">
	    <li class="nav-item col-6 mb-5 p-0">
		      <a class="nav-link px-0 border text-center border" href="<%= search_posts_path %>">投稿</a>
		    </li>
		    <li class="nav-item col-6 mb-5 p-0">
	      		<a class="nav-link active px-0 border text-center border" href="#">ユーザー</a>
		    </li>
		</ul>

   	<div id="scroll">
		<%= render "user_list", users: @search_users %>
		<%= link_to_next_page @search_users, '次のページ', class: "next" %>
	</div>
	<button class="button" type="button">もっと見る</button>
	<%= render "shared/scroll_setting" %>
</div>

app/views/users/show.html.erb
<div class="container">
    <%= render "shared/notice", notice: notice %>
    <%= render "shared/alert", alert: alert %>

    <div class="media col-6 d-flex mx-auto my-5">
        <div class="user-image col-4 d-flex">
            <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "150x150", class: "rounded-circle" %>
        </div>
        <div class="user-inf media-body col-8">
            <p><u><%= @user.name %></u></p>
            <% if user_signed_in? && @user != current_user %>
                <div class="follow_<%= @user.id %>">
                    <%= render "users/follow_form", user: @user %>
                </div>
            <% else %>
                <%= link_to 'プロフィール編集', edit_user_path(@user), class: 'btn btn-outline-dark' %>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
            <% end %>
            <u><%= @user.introduction %></u>
        </div>
    </div>
    <div class="row mt-5">
        <ul class="nav nav-pills col-8 mx-auto mt-5 p-0" role="tablist">
            <li class="nav-item col-3 p-0">
                <a class="nav-link active  px-0 border text-center border" id="my-tab" data-toggle="tab" href="#my" role="tab" aria-controls="my" aria-selected="true">投稿 <%= @user.posts.count %></a>
            </li>
            <li class="nav-item col-3 p-0">
                <a class="nav-link  px-0 border text-center border" id="follow-tab" data-toggle="tab" href="#follow" role="tab" aria-controls="follow" aria-selected="false">フォロー <%= @user.follower.count %></a>
            </li>
            <li class="nav-item col-3 p-0">
                <a class="nav-link  px-0 border text-center border" id="follower-tab" data-toggle="tab" href="#follower" role="tab" aria-controls="follower" aria-selected="false">フォロワー <%= @user.followed.count %></a>
            </li>
            <li class="nav-item col-3 p-0">
            <a class="nav-link  px-0 border text-center border" id="like-tab" data-toggle="tab" href="#like" role="tab" aria-controls="like" aria-selected="false">いいね <%= @user.likes.count %></a>
            </li>
        </ul>
    </div>

    <div class="row mt-5">
        <div class="tab-content w-100">
            <!-- current_userの投稿 -->
            <div class="tab-pane fade show active" id="my" role="tabpanel" aria-labelledby="my-tab">
                <% unless @my_posts.blank? %>
                    <div id="my-scroll">
                        <!-- TODO 部分テンプレート化 -->
                        <div class="my-scroll">
                            <div class="row">
                                <% @my_posts.each do |my_post| %>
                                    <%= render "posts/post_card", post: my_post %>
                                <% end %>
                            </div>
                        </div>
                        <%= link_to_next_page @my_posts, '次のページ', class: "my-next" %>
                    </div>
                    <!-- TODO 部分テンプレート化 -->
                    <button class="my-button" type="button">もっと見る</button>
                    <%= render "shared/scroll_setting" %>
                <% else %>
                    <p>投稿がありません。</p>
                <% end %>
            </div>

            <!-- フォローリスト -->
            <div class="tab-pane fade show" id="follow" role="tabpanel" aria-labelledby="follow-tab">
                <div id="follow-scroll">
                    <!-- TODO 部分テンプレート化 -->
                    <div class="follow-scroll">
                        <div class="row">
                            <% @follow_users.each do |follow_user| %>
                                <%= render "users/user_card", user: follow_user %>
                            <% end %>
                        </div>
                    </div>
                    <%= link_to_next_page @follow_users, '次のページ', class: "follow-next" %>
                </div>
                <button class="follow-button" type="button">もっと見る</button>
                <%= render "shared/scroll_setting" %>
            </div>

            <!-- フォロワーリスト -->
            <div class="tab-pane fade show" id="follower" role="tabpanel" aria-labelledby="follower-tab">
                <div id="follower-scroll">
                    <!-- TODO 部分テンプレート化 -->
                    <div class="follower-scroll">
                        <div class="row">
                            <% @follower_users.each do |follower_user| %>
                                <%= render "users/user_card", user: follower_user %>
                            <% end %>
                        </div>
                    </div>
                    <%= link_to_next_page @follower_users, '次のページ', class: "follower-next" %>
                </div>
                <button class="follower-button" type="button">もっと見る</button>
                <%= render "shared/scroll_setting" %>
            </div>

            <!-- いいねした投稿 -->
            <div class="tab-pane fade show active" id="like" role="tabpanel" aria-labelledby="like-tab">
                <% unless @like_posts.blank? %>
                    <div id="like-scroll">
                        <!-- TODO 部分テンプレート化 -->
                        <div class="like-scroll">
                            <div class="row">
                                <% @like_posts.each do |like_post| %>
                                    <%= render "posts/post_card", post: like_post.post %>
                                <% end %>
                            </div>
                        </div>
                        <%= link_to_next_page @like_posts, '次のページ', class: "like-next" %>
                    </div>
                    <!-- TODO 部分テンプレート化 -->
                    <button class="like-button" type="button">もっと見る</button>
                    <%= render "shared/scroll_setting" %>
                <% else %>
                    <p>投稿がありません。</p>
                <% end %>
            </div>
        </div>
    </div>
</div>

<script>
    $("#like").removeClass("active");
    $("#like").removeClass("show");
</script>