config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get '/users/guest_sign_in', to: 'users/sessions#guest_login'
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image
  acts_as_taggable

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  validates :text, length: { maximum: 140 }
  validates :rate, presence: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :search
  before_action :admin_limit, only: [:new, :create]

  def index
    # フォローユーザーの投稿取得
    follow_users = current_user.following_user
    @timeline_posts = Post.where(user_id: follow_users).order(created_at: "DESC").
      page(params[:page]).per(3)
    # 新着順で投稿取得
    @arrival_posts = Post.order(created_at: "DESC").page(params[:page]).per(9)
    # 人気順で投稿取得
    @popular_posts = Post.left_joins(:likes).group('posts.id').order('count(likes.post_id) DESC').
      page(params[:page]).per(9)
  end

  def new
    @post = Post.new
    @post.post_images.build
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path, notice: "投稿しました。"
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "投稿を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:alert] = "投稿を削除しました。"
    if params[:admin].present?
      redirect_back(fallback_location: posts_path)
    else
      redirect_to posts_path
    end
  end

  def search
    @search = Post.ransack(params[:q])
    # タグ絞り込み処理
    if params[:tag_name]
      @search_posts = Post.tagged_with("#{params[:tag_name]}").order(created_at: "DESC").
        page(params[:page]).per(9)
    else
      @search_posts = @search.result.order(created_at: "DESC").page(params[:page]).per(9)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :rate, :tag_list, post_images_images: [])
  end

  def admin_limit
    if current_user.admin?
      redirect_to posts_path, alert: "管理者ユーザーは新規投稿できません。"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_card_footer.html.erb
<div class="card-foot d-flex px-0 pt-0 pb-3 bg-white">
	<div class="user_inf mr-auto">
		<span class="img" alt="Card image">
			<%= link_to user_path(post.user) do %>
				<%= attachment_image_tag post.user, :profile_image, fallback: "no_image.jpg", size: "55x55", class: "rounded-circle" %>
			<% end %>
		</span>
		<span class="nav-item post-name ml-1" style="font-size: 1.1em;">
			<%= link_to post.user.name, user_path(post.user), class: "text-dark" %>
		</span>
	</div>

	<div class="post_inf pt-4">
		<% if user_signed_in? %>
			<% if current_user.admin? %>
				<%= link_to '削除', post_path(post, admin: "admin"), method: :delete, class: 'btn btn-danger btn-sm' %>
			<% end %>
		<% end %>
		<%= link_to "コメント #{post.post_comments.count} 件", post_path(post), class: "small text-secondary" %>
		<%= link_to "いいね! #{post.likes.count} 件", post_path(post), class: "small text-secondary" %>
	</div>
</div>

app/views/posts/_card_header.html.erb
<div class="card-head d-flex mb-1 p-0 bg-white">
	<div class="post-title mr-auto ml-2"><%= link_to post.title, post_path(post), class: "text-dark font-weight-bold" %></div>
	<div class="post-tag">
		<% post.tag_list.each do |tag| %>
			<div class="badge badge-dark mr-1 p-2">
				<%= link_to tag, search_posts_path(tag_name: tag), class: "text-white" %>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/_comment_form.html.erb
<div class="mx-auto">
	<%= form_with model: [post, comments] do |f| %>
		<%= f.text_field :comment, class: "textarea" %><br>
		<%= f.submit 'コメントする', class: "btn btn-warning text-white mt-3" %>
	<% end %>
</div>

app/views/posts/_comment_index.html.erb
<% post.post_comments.each do |post_comment| %>
	<div class="comment ml-5">
		<span><%= post_comment.comment %></span>

		<span class="text-right"><%= post_comment.created_at.strftime("%Y/%m/%d %H:%M") %></span>
		<span class="mx-2"><%= post_comment.user.name %></span>
		<% if current_user == @post.user || current_user.admin? %>
			<%= link_to '削除', post_post_comment_path(post, post_comment), method: :delete, remote: true, class: 'btn btn-outline-danger' %>
		<% end %>
	</div>
<% end %>

app/views/posts/_post_card.html.erb
<div class="col-4 bg-white">
	<div class="card border-0 mt-3">
		<%= render "posts/card_header", post: post %>
		<%= render "posts/post_card_body", post: post %>
		<%= render "posts/card_footer", post: post %>
	</div>
</div>

app/views/posts/_post_card_body.html.erb
<div class="card-body p-0">
	<div class="img" alt="Card image">
		<%= link_to post_path(post) do %>
			<%= attachment_image_tag post.post_images.first, :image, fallback: "no_image.jpg", size: "360x360", class: "rounded-lg" %>
		<% end %>
	</div>
</div>

app/views/posts/_post_card_footer.html.erb
<div class="card-footer d-flex px-0 pt-0 pb-3 bg-white">
	<div class="user_inf mr-auto">
		<span class="img" alt="Card image">
			<%= attachment_image_tag post.user, :profile_image, fallback: "no_image.jpg", size: "55x55", class: "rounded-circle" %>
		</span>
		<span class="nav-item post-name ml-1" style="font-size: 1.1em;">
			<%= post.user.name %>
		</span>
	</div>

	<div class="post_inf pt-4">
		<% if user_signed_in? %>
			<% if current_user.admin? %>
				<%= link_to '削除', post_path(post, admin: "admin"), method: :delete, class: 'btn btn-danger' %>
			<% end %>
		<% end %>
		<span class="small text-secondary">コメント <%= post.post_comments.count %> 件</span>
		<span class="small text-secondary">いいね! <%= post.likes.count %></span>
	</div>
</div>

app/views/posts/_timeline_card.html.erb
<div class="col-6 mx-auto bg-white">
	<div class="card border-0 mt-3">
		<%= render "posts/card_header", post: post %>
		<%= render "posts/timeline_card_body", post: post %>
		<%= render "posts/card_footer", post: post %>
	</div>
</div>

app/views/posts/_timeline_card_body.html.erb
<div class="card-body p-0">
	<div class="img bxslider" alt="Card image">
		<% post.post_images.each do |image| %>
			<%= attachment_image_tag image, :image, fallback: "no_image.jpg", size: "550x550", class: "rounded-lg" %>
		<% end %>
	</div>
	<div class="post-text mt-3"><%= post.text %></div>
</div>

<script>
	onbxslider();
</script>

app/views/posts/edit.html.erb
<div class="container">
	<div class="col-6 d-flex mx-auto">
		<%= form_with model: @post, local: true do |f| %>
			<%= render "shared/error_messages", model: f.object %>

			<h2 class="title d-flex"><span class="border-bottom mx-auto">投稿編集</span></h2>
			<div class="post-image d-flex mt-3">
				<div class="form-group">
                    <label>
                    <div class="form_main">
                    	<% @post.post_images.each do |image| %>
                        	<%= attachment_image_tag image, :image, fallback: "no_image.jpg", size: "150x150", class: 'image_form' %>
                        <% end %>
                    </div>
                    <div class="form_sub">
		                <%= f.attachment_field :post_images_images, multiple: true, class: 'form-control-file' %>
                    </div>
                    </label>
                </div>
			</div>

			<div class="post-title">
				<div class="form-group">
					<%= f.label :title, "タイトル" %>
					<%= f.text_field :title, class: 'form-control' %>
				</div>
			</div>

			<div class="post-tag">
				<div class="form-group">
					<%= f.label :tag_list %>
					<%= f.text_area :tag_list, value: @post.tag_list.join(','), class: 'form-control' %>
				</div>
			</div>

			<div class="post-text">
				<div class="form-group">
					<%= f.label :text, "本文" %>
					<%= f.text_area :text, class: 'form-control' %>
				</div>
			</div>

			<div class="post-rate">
				<div class="form-group">
					<%= f.hidden_field :rate, class: 'form-control' %>
					<div id="star-rate"></div>
				</div>
			</div>

			<div class="submit mt-5">
				<%= link_to 'キャンセル', post_path, class: "btn btn-outline-dark" %>
				<%= f.submit '変更を保存', class: 'btn-lg btn-outline-dark ml-3' %>
			</div>
		<% end %>
	</div>
</div>

<script>
$('#star-rate').raty({
	path: '/assets/',
	size: 50,
	half: true,
	scoreName: 'post[rate]',
	score: <%= @post.rate %>
})
</script>

app/views/posts/index.html.erb
<div class="container">
	<%= render "shared/notice", notice: notice %>
    <%= render "shared/alert", alert: alert %>


	<ul class="nav nav-pills col-8 mx-auto mt-1 p-0" role="tablist">
	  <li class="nav-item col-4 p-0">
	    <a class="nav-link active px-0 border text-center border" id="timeline-tab" data-toggle="pill" href="#timeline" role="tab" aria-controls="timeline" aria-selected="true">タイムライン</a>
	  </li>
	  <li class="nav-item col-4 p-0">
	    <a class="nav-link px-0 border text-center border" id="arrival-tab" data-toggle="pill" href="#arrival" role="tab" aria-controls="arrival" aria-selected="false">新着</a>
	  </li>
	  <li class="nav-item col-4 p-0">
	    <a class="nav-link px-0 border text-center border" id="popular-tab" data-toggle="pill" href="#popular" role="tab" aria-controls="popular" aria-selected="false">人気</a>
	  </li>
	</ul>


	<div class="row mt-5">
		<div class="tab-content w-100">
			<!-- タイムライン -->
		  	<div class="tab-pane fade show active" id="timeline" role="tabpanel" aria-labelledby="timeline-tab">
		  		<div id="timeline-scroll">
		  			<!-- TODO 部分テンプレート化 -->
		  			<div class="timeline-scroll">
						<div class="row">
							<% @timeline_posts.each do |post| %>
								<%= render "posts/timeline_card", post: post %>
							<% end %>
						</div>
					</div>
					<%= link_to_next_page @timeline_posts, '次のページ', class: "timeline-next" %>
				</div>
				<!-- TODO 部分テンプレート化 -->
				<%= render "shared/scroll_setting" %>
			</div>

			<!-- 新着 -->
			<div class="tab-pane fade show active" id="arrival" role="tabpanel" aria-labelledby="arrival-tab">
	  			<div id="arrival-scroll">
	  				<!-- TODO 部分テンプレート化 -->
	  				<div class="arrival-scroll">
						<div class="row">
							<% @arrival_posts.each do |post| %>
								<%= render "posts/post_card", post: post %>
							<% end %>
						</div>
					</div>
					<%= link_to_next_page @arrival_posts, '次のページ', class: "arrival-next" %>
	  			</div>
	  			<!-- TODO 部分テンプレート化 -->
	  			<button class="arrival-button" type="button">もっと見る</button>
				<%= render "shared/scroll_setting" %>
		  	</div>

		  	<!-- 人気 -->
			<div class="tab-pane fade show active" id="popular" role="tabpanel" aria-labelledby="popular-tab">
				<div id="popular-scroll">
					<!-- TODO 部分テンプレート化 -->
	  				<div class="popular-scroll">
						<div class="row">
							<% @popular_posts.each do |post| %>
								<%= render "posts/post_card", post: post %>
							<% end %>
						</div>
					</div>
	  				<%= link_to_next_page @popular_posts, '次のページ', class: "popular-next" %>
	  			</div>
	  			<!-- TODO 部分テンプレート化 -->
	  			<button class="popular-button" type="button">もっと見る</button>
	  			<%= render "shared/scroll_setting" %>
			</div>
		</div>
	</div>
</div>

<script>
	$("#arrival").removeClass("active");
	$("#arrival").removeClass("show");
	$("#popular").removeClass("active");
	$("#popular").removeClass("show");
</script>

app/views/posts/new.html.erb
<div class="container">
	<div class="col-6 d-flex mx-auto">
		<%= form_with model: @post, local: true do |f| %>
			<%= render "shared/error_messages", model: f.object %>

			<h2 class="title d-flex"><span class="border-bottom mx-auto">新規投稿</span></h2>

			<div class="post-image d-flex mt-3">
				<div class="form-group">
					<label>
						<div class="form_main">
							<%= image_tag 'no_image.jpg', size: "150x150"  %>
		                </div>
		                <div class="form_sub">
		                    <%= f.attachment_field :post_images_images, multiple: true, required:true, class: 'form-control-file' %>
		                </div>
					</label>
				</div>
			</div>

			<div class="post-title">
				<div class="form-group">
					<%= f.label :title, "タイトル" %>
					<%= f.text_field :title, class: 'form-control' %>
				</div>
			</div>

			<div class="post-tag">
				<div class="form-group">
					<%= f.label :tag_list, "タグ" %>
					<%= f.text_area :tag_list, value: @post.tag_list.join(','), class: 'form-control' %>
				</div>
			</div>

			<div class="post-text">
				<div class="form-group">
					<%= f.label :text, "本文" %>
					<%= f.text_area :text, class: 'form-control' %>
				</div>
			</div>

			<div class="post-rate">
				<div class="form-group">
					<%= f.hidden_field :rate, class: 'form-control' %>
					<div id="star-rate"></div>
				</div>
			</div>

			<div class="submit">
				<%= f.submit "投稿する", class: 'btn-lg btn-outline-dark' %>
			</div>
		<% end %>
	</div>
</div>

<script>
$('#star-rate').raty({
	path: '/assets/',
	size: 50,
	half: true,
	scoreName: 'post[rate]'
})
</script>

app/views/posts/search.html.erb
<div class="container">
	<%= render "shared/alert", alert: alert %>

	<div class="row">
		<div class="col-6 mx-auto my-3">
			<%= search_form_for @search, url: search_posts_path do |f| %>
	        	<%= f.search_field :title_or_text_or_user_name_cont, class: "form-control", placeholder: "投稿を検索" %>
	        	<%= f.submit '検索', class: "btn btn-success d-none" %>
	     	<% end %>
	    </div>
   	</div>

   	<ul class="nav nav-pills col-8 mx-auto my-4 p-0" role="tablist">
	    <li class="nav-item col-6 p-0">
	      <a class="nav-link active  px-0 border text-center border" href="#">投稿</a>
	    </li>
	    <li class="nav-item col-6 p-0">
	      <a class="nav-link  px-0 border text-center border" href="<%= search_users_path %>">ユーザー</a>
	    </li>
	</ul>

	<div id="scroll">
		<%= render "posts/post_list", posts: @search_posts %>
		<%= link_to_next_page @search_posts, '次のページ', class: "next" %>
	</div>
	<button class="button" type="button">もっと見る</button>
	<%= render "shared/scroll_setting" %>
</div>

app/views/posts/show.html.erb
<div class="container">
	<% if @comment.present? %>
		<%= render "shared/error_messages", model: @comment %>
	<% end %>
	<%= render "shared/notice", notice: notice %>

	<!-- ポストカード ヘッダー・ボディー -->
	<div class="post-card col-7 mx-auto">
		<div class="border-0 mt-3">
			<%= render "posts/card_header", post: @post %>
			<%= render "posts/timeline_card_body", post: @post %>
		</div>
	</div>

	<!-- ポストカード フッター -->
	<div class="post-foot col-7 d-flex mx-auto px-0 py-3 bg-white">
		<div class="user_inf mr-auto ml-2">
			<span class="img" alt="Card image">
				<%= attachment_image_tag @post.user, :profile_image, fallback: "no_image.jpg", size: "55x55", class: "rounded-circle" %>
			</span>
			<span class="nav-item post-name ml-1" style="font-size: 1.1em;">
				<%= @post.user.name %>
			</span>
		</div>
		<div class="post_inf pt-4">
			<span class="small text-secondary"><%= @post.created_at.strftime("%Y/%m/%d %H:%M") %></span>
			<span class="small text-secondary">コメント <%= @post.post_comments.count %> 件</span>
			<div class="post_<%= @post.id %>"><%= render "likes/like", post: @post %></div>
		</div>
	</div>

	<!-- 投稿編集・削除ボタン -->
	<div class="link-destination col-7 d-flex mx-auto my-5">
		<% if current_user == @post.user || current_user.admin? %>
			<%= link_to '投稿編集', edit_post_path(@post), class: 'btn btn-outline-dark mx-auto' %>
			<%= link_to '削除', @post, method: :delete, class: 'btn btn-outline-danger' %>
		<% end %>
	</div>

	<!-- コメント -->
	<div class="comment-form col-10 d-flex m-auto" style="margin-top: 80px;">
		<%= render "posts/comment_form", post: @post, comments: @comments %>
	</div>
	<div class="comment-title col-10 mt-4">
		<h4>コメント一覧</h4>
	</div>
	<div class="comment-index col-10 mr-0">
		<%= render "posts/comment_index", post: @post %>
	</div>
</div>

<script>
$('#star-rate').raty({
	path: '/assets/',
	size: 50,
	half: true,
	readOnly: true,
	scoreName: 'post[rate]',
	score: <%= @post.rate %>
})
</script>